package awscostexplorer

// ServiceNameMap maps common shorthand names to AWS Cost Explorer service names.
var ServiceNameMap = map[string]string{
	"ec2":            "Amazon Elastic Compute Cloud - Compute",
	"ecr":            "Amazon EC2 Container Registry (ECR)",
	"eks":            "Amazon Elastic Container Service for Kubernetes",
	"elb":            "Amazon Elastic Load Balancing",
	"ec2-other":      "EC2 - Other",
	"s3":             "Amazon Simple Storage Service",
	"rds":            "Amazon Relational Database Service",
	"dynamodb":       "Amazon DynamoDB",
	"lambda":         "AWS Lambda",
	"cloudwatch":     "Amazon CloudWatch",
	"cloudfront":     "Amazon CloudFront",
	"elasticache":    "Amazon ElastiCache",
	"sns":            "Amazon Simple Notification Service",
	"sqs":            "Amazon Simple Queue Service",
	"ecs":            "Amazon Elastic Container Service",
	"vpc":            "Amazon Virtual Private Cloud",
	"route53":        "Amazon Route 53",
	"apigateway":     "Amazon API Gateway",
	"redshift":       "Amazon Redshift",
	"savingsplans":   "Savings Plans",
	"glue":           "AWS Glue",
	"kinesis":        "Amazon Kinesis",
	"quicksight":     "Amazon QuickSight",
	"waf":            "AWS WAF",
	"backup":         "AWS Backup",
	"firehose":       "Amazon Kinesis Firehose",
	"stepfunctions":  "AWS Step Functions",
	"kms":            "AWS Key Management Service",
	"secretsmanager": "AWS Secrets Manager",
	"ssm":            "AWS Systems Manager",
	"location":       "Amazon Location Service",
}
